Rappels

In [7]:
import numpy as np
from pandas import DataFrame, NamedAgg
df = DataFrame({"key1" : ["a", "a", "b", "b", "a"],
                    "key2" : ["one", "two", "one", "two", "one"],
                    "data1" : np.random.randn(5),
                    "data2" : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.871283  0.244137
1    a  two  0.187272 -0.569262
2    b  one -0.843492 -0.494092
3    b  two  1.331969 -0.892482
4    a  one -1.049829  0.060242

In [8]:
means = df.groupby(["key1", "key2"]).mean()
means

              data1     data2
key1 key2
a    one  -0.089273  0.152189
     two   0.187272 -0.569262
b    one  -0.843492 -0.494092
     two   1.331969 -0.892482

In [9]:
df.groupby(["key1", "key2"]).agg(
    mean_data1=NamedAgg(column="data1", aggfunc="mean"),
    mean_data2=NamedAgg(column="data2", aggfunc="mean")
)

           mean_data1  mean_data2
key1 key2
a    one    -0.089273    0.152189
     two     0.187272   -0.569262
b    one    -0.843492   -0.494092
     two     1.331969   -0.892482

In [3]:
# Idée générale de la syntaxe
# grouper selon une clé
df.groupby("key1")[["data1", "data2"]].mean()

# Question : Pourquoi a-t-on besoin de préciser [["data1", "data2"]] ?

         data1     data2
key1
a     0.244227 -0.467949
b    -0.037611 -0.637524

In [4]:
# grouper selon 2 clés
df.groupby(["key1", "key2"]).sum()

              data1     data2
key1 key2
a    one   0.036840 -1.553745
     two   0.695841  0.149897
b    one  -0.997709 -0.285609
     two   0.922486 -0.989440

In [5]:
# Groupby et effectuer plusieurs opérations
df.groupby(["key1", "key2"])["data1"].agg(["mean", "count", "min", "max"])

               mean  count       min       max
key1 key2
a    one   0.018420      2 -0.336159  0.372998
     two   0.695841      1  0.695841  0.695841
b    one  -0.997709      1 -0.997709 -0.997709
     two   0.922486      1  0.922486  0.922486

In [6]:
# Important : .agg() peut accepter des listes de built-in functions, ou même des fonctions définies par l'utilisateur

Exercices

In [ ]:
# Avec les données du Titanic
from pandas import read_csv
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = read_csv(url)
df_titanic

In [ ]:
# Groupby sex et compter le nombre dans chaque catégorie

In [ ]:
# Groupby sex et afficher le prix moyen du ticket


# ou bien

In [ ]:
# Groupby sex et Pclass et afficher le prix min et max du ticket pour chaque groupe