# Rappels

Jointure

In [3]:
from pandas import DataFrame
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [4]:
df2 = DataFrame({'key': ['a', 'b', 'd'], 'data2': range(3)})
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [5]:
# Par défaut, la jointure se fait sur la clé commune, avec le mode "left"
from pandas import merge
merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [6]:
# S'il n'y a pas de clé commune 
df3 = DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df4 = DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})

merge(df3, df4, left_on="lkey", right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [7]:
# Différents modes de jointure
merge(df1, df2, how="right")

  key  data1  data2
0   a    2.0      0
1   a    4.0      0
2   a    5.0      0
3   b    0.0      1
4   b    1.0      1
5   b    6.0      1
6   d    NaN      2

Concatenation

In [8]:
from pandas import concat
concat([df1, df2], axis =1)["key"]

  key  key
0   b    a
1   b    b
2   a    d
3   c  NaN
4   a  NaN
5   a  NaN
6   b  NaN

In [9]:
# Par défaut, la concaténation est verticale
concat([df1, df2])

  key  data1  data2
0   b    0.0    NaN
1   b    1.0    NaN
2   a    2.0    NaN
3   c    3.0    NaN
4   a    4.0    NaN
5   a    5.0    NaN
6   b    6.0    NaN
0   a    NaN    0.0
1   b    NaN    1.0
2   d    NaN    2.0

In [10]:
concat([df1, df2], axis=1)

  key  data1  key  data2
0   b      0    a    0.0
1   b      1    b    1.0
2   a      2    d    2.0
3   c      3  NaN    NaN
4   a      4  NaN    NaN
5   a      5  NaN    NaN
6   b      6  NaN    NaN

In [22]:
# Concat sans contrainte d'Index
import numpy as np
df_1 = DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df_2 = DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [23]:
df_1

          a         b         c         d
0  0.694511  1.340544 -0.208500  0.091859
1 -0.551282  0.534440  0.405520  1.469915
2  0.142706 -0.544681 -0.202828 -1.275143

In [24]:
df_2

          b         d         a
0  0.201428  0.151131  0.099721
1 -0.119671 -0.681979  0.981423

In [25]:
concat([df_1, df_2])

          a         b         c         d
0  0.694511  1.340544 -0.208500  0.091859
1 -0.551282  0.534440  0.405520  1.469915
2  0.142706 -0.544681 -0.202828 -1.275143
0  0.099721  0.201428       NaN  0.151131
1  0.981423 -0.119671       NaN -0.681979

In [26]:
concat([df_1, df_2], ignore_index=True)

          a         b         c         d
0  0.694511  1.340544 -0.208500  0.091859
1 -0.551282  0.534440  0.405520  1.469915
2  0.142706 -0.544681 -0.202828 -1.275143
3  0.099721  0.201428       NaN  0.151131
4  0.981423 -0.119671       NaN -0.681979

In [11]:
# Concat avec mode de jointure
from pandas import Series
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e']) 
s3 = Series([5, 6], index=['f', 'g'])
s4 = concat([s1 * 5, s3])

In [12]:
s1

a    0
b    1
dtype: int64

In [13]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [20]:
df = concat([s1, s4])
df["b"]

b    1
b    5
dtype: int64

In [15]:
concat([s1, s4], axis=1, join='inner')

   0  1
a  0  0
b  1  5

In [16]:
concat([s1, s4], axis=1, join='outer')

     0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

Exercice

In [ ]:
# A partir des données du Titanic
# Créer une nouvelle colonne "prix moyen custom" qui correspond au prix moyen par catégorie "Pclass" et "Sex"
from pandas import read_csv
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = read_csv(url).sample(100)

# Indice : pourquoi cet exercice se trouve-t-il dans cette catégorie ?

In [ ]:
# Bonus
# Une meilleure façon de faire : avec la fonction .transform()